// import Banner from "../../components/Banner";
// import Header from "../../components/Header";
import "../../styles/globals.css";
// import Footer from "./components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" bg-black">
        {/* <Header /> */}
        {/* <div
          className="mx-auto max-w-full"
          style={{ backgroundImage: "url(/images/background-home.jpg)" }}
        > */}
        <div className=" mx-auto max-w-7xl bg-blend-overlay backdrop-blur">
          <div className="mx-auto max-w-full p-14">{children}</div>
        </div>
        {/* </div> */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
